NAME: EVENT_TEST
on: [push, issue_comment, issues, label, pull_request, pull_request_review, pull_request_review_comment, push, release]

jobs:
  output:
    name: output info
    runs-on: ubuntu-latest
    steps:
      - name: output environment variables
        run: env
      - name: output payload
        run: jq -C . $GITHUB_EVENT_PATH
